#ifndef CONF_H
#define CONF_H

#include <SDL2/SDL.h>

// window options.
#define CONF_WND_TITLE "Cubic Jumping"
#define CONF_WND_WIDTH 800
#define CONF_WND_HEIGHT 600
#define CONF_WND_FLAGS 0
#define CONF_REND_FLAGS 0

// default options.
#define CONF_OPTIONS_FILE "options.conf"
#define CONF_DEFAULT_K_LEFT SDLK_LEFT
#define CONF_DEFAULT_K_RIGHT SDLK_RIGHT
#define CONF_DEFAULT_K_JUMP SDLK_UP
#define CONF_DEFAULT_K_DASH_DOWN SDLK_DOWN
#define CONF_DEFAULT_K_POWERJUMP SDLK_x
#define CONF_DEFAULT_K_MENU SDLK_ESCAPE
#define CONF_DEFAULT_K_EDITOR_LEFT SDLK_LEFT
#define CONF_DEFAULT_K_EDITOR_RIGHT SDLK_RIGHT
#define CONF_DEFAULT_K_EDITOR_UP SDLK_UP
#define CONF_DEFAULT_K_EDITOR_DOWN SDLK_DOWN
#define CONF_DEFAULT_SFX_VOLUME 0.3f

// gamerule options.
#define CONF_TICK_MS 10
#define CONF_FRICTION 1.22f
#define CONF_WALL_SLIDE_FRICTION 1.25f
#define CONF_DRAG 1.005f
#define CONF_PLAYER_SIZE 0.8f
#define CONF_PLAYER_SPEED 0.025f
#define CONF_PLAYER_AIR_SPEED 0.0025f
#define CONF_PLAYER_JUMP_FORCE 0.3f
#define CONF_PLAYER_WALLJUMP_FORCE_X 0.15f
#define CONF_PLAYER_WALLJUMP_FORCE_Y 0.25f
#define CONF_PLAYER_POWERJUMP_FORCE_X 0.4f
#define CONF_PLAYER_POWERJUMP_FORCE_Y 0.2f
#define CONF_PLAYER_DASH_DOWN_SPEED 0.55f
#define CONF_PLAYER_DEATH_TICKS 100
#define CONF_GRAVITY 0.01f
#define CONF_RESTITUTION 1.1f
#define CONF_LAUNCH_FORCE 0.8f
#define CONF_WALL_LAUNCH_FORCE_X 0.6f
#define CONF_WALL_LAUNCH_FORCE_Y 0.4f

// visual options.
#define CONF_DRAW_SCALE 50
#define CONF_SHOW_TRIGGERS 0 // 1 = show triggers, 0 = don't.
#define CONF_COLOR_BG {239, 239, 239}
#define CONF_COLOR_BG_SQUARE {232, 232, 232}
#define CONF_COLOR_BG_DVD_A {180, 230, 0}
#define CONF_COLOR_BG_DVD_B {0, 230, 180}
#define CONF_COLOR_PLAYER {255, 0, 0}
#define CONF_COLOR_TRIGGER_MSG {255, 179, 0}
#define CONF_COLOR_TRIGGER_KILL {210, 0, 0}
#define CONF_COLOR_TRIGGER_MSG_TERM {230, 0, 210}
#define CONF_COLOR_TRIGGER_CAP_ENABLE {20, 200, 20}
#define CONF_COLOR_TRIGGER_CAP_DISABLE {20, 20, 200}
#define CONF_COLOR_TRIGGER_OPACITY 128
#define CONF_COLOR_PLAYER_TRACE_A {245, 164, 162}
#define CONF_COLOR_PLAYER_TRACE_B {146, 100, 154}
#define CONF_COLOR_PLAYER_SHARD_A {255, 0, 0}
#define CONF_COLOR_PLAYER_SHARD_B {128, 0, 0}
#define CONF_COLOR_AIR_PUFF {190, 190, 190}
#define CONF_COLOR_GROUND {0, 0, 0}
#define CONF_COLOR_KILL {100, 0, 0}
#define CONF_COLOR_BOUNCE {0, 150, 200}
#define CONF_COLOR_LAUNCH {0, 255, 130}
#define CONF_COLOR_END_ON {240, 190, 0}
#define CONF_COLOR_SWITCH_OFF {128, 140, 255}
#define CONF_COLOR_SWITCH_ON {255, 140, 255}
#define CONF_COLOR_END_OFF {120, 95, 0}
#define CONF_COLOR_SLIPPERY {80, 180, 170}
#define CONF_COLOR_TEXT {255, 255, 255}
#define CONF_COLOR_TEXT_OUTLINE {0, 0, 0}
#define CONF_COLOR_TEXT_BOX {70, 70, 70}
#define CONF_COLOR_TEXT_BOX_OPACITY 210
#define CONF_COLOR_BUTTON {110, 110, 110}
#define CONF_COLOR_BUTTON_HOVERED {190, 190, 190}
#define CONF_COLOR_BUTTON_PRESSED {10, 10, 10}
#define CONF_COLOR_TEXT_FIELD {110, 110, 110}
#define CONF_COLOR_TEXT_FIELD_HOVERED {190, 190, 190}
#define CONF_COLOR_TEXT_FIELD_SELECTED {10, 10, 10}
#define CONF_COLOR_TEXT_FIELD_CURSOR {240, 240, 240}
#define CONF_COLOR_SLIDER {110, 110, 110}
#define CONF_COLOR_SLIDER_HOVERED {190, 190, 190}
#define CONF_COLOR_SLIDER_PRESSED {10, 10, 10}
#define CONF_COLOR_SLIDER_CURSOR {240, 240, 240}
#define CONF_COLOR_OUTLINE {210, 210, 210}
#define CONF_COLOR_EDITOR_SAVED {0, 255, 0}
#define CONF_COLOR_EDITOR_UNSAVED {255, 0, 0}
#define CONF_COLOR_EDITOR_BOUNDARY {0, 255, 255}
#define CONF_COLOR_EDITOR_BOUNDARY_OPACITY 100
#define CONF_COLOR_EDITOR_SAVED {0, 255, 0}
#define CONF_COLOR_EDITOR_UNSAVED {255, 0, 0}
#define CONF_COLOR_LEVEL_END_BG {30, 30, 30}
#define CONF_COLOR_SEQUENCE_BG {30, 30, 30}
#define CONF_COLOR_SEQUENCE_HL {95, 95, 95}
#define CONF_COLOR_AWAITING_INPUT_BG {0, 0, 0}
#define CONF_BG_SQUARE_SIZE 128
#define CONF_BG_SQUARE_GAP 16
#define CONF_BG_SQUARE_SPEED_X 0.2f
#define CONF_BG_SQUARE_SPEED_Y 0.1f
#define CONF_BG_DVD_SIZE 370
#define CONF_BG_DVD_SPEED 1
#define CONF_BG_DVD_COL_SPEED 0.005f
#define CONF_CAM_SPEED 0.08f
#define CONF_CAM_LOOKAHEAD_X 20.0f
#define CONF_CAM_LOOKAHEAD_Y 3.0f
#define CONF_CAM_ZOOM_SPEED 0.025f
#define CONF_CAM_MIN_ZOOM 0.3f
#define CONF_CAM_MAX_ZOOM 0.9f
#define CONF_MAX_PARTICLES 512
#define CONF_PLAYER_TRACE_LIFETIME 80
#define CONF_PLAYER_TRACE_SIZE_A 0.8f
#define CONF_PLAYER_TRACE_SIZE_B 0.0f
#define CONF_PLAYER_TRACE_SPAWN_TICKS 2
#define CONF_PLAYER_SHARD_LIFETIME_RANGE 120
#define CONF_PLAYER_SHARD_SPEED_X_RANGE 0.2f
#define CONF_PLAYER_SHARD_SPEED_Y_RANGE 0.3f
#define CONF_PLAYER_SHARD_SIZE_A 0.7f
#define CONF_PLAYER_SHARD_SIZE_B 0.3f
#define CONF_PLAYER_SHARD_CNT 40
#define CONF_AIR_PUFF_LIFETIME_RANGE 30
#define CONF_AIR_PUFF_SPEED_X_RANGE 0.2f
#define CONF_AIR_PUFF_SPEED_Y_RANGE 0.1f
#define CONF_AIR_PUFF_SIZE_A 0.5f
#define CONF_AIR_PUFF_SIZE_B 0.2f
#define CONF_AIR_PUFF_CNT 15
#define CONF_TEXT_SCALE 4
#define CONF_TEXT_OUTLINE_SCALE 2
#define CONF_TEXT_BOX_PADDING 10
#define CONF_TEXT_BOX_HEIGHT 140
#define CONF_BUTTON_PADDING 5
#define CONF_TEXT_FIELD_PADDING 5
#define CONF_TEXT_FIELD_CURSOR_WIDTH 3
#define CONF_SLIDER_CURSOR_WIDTH 6
#define CONF_CREDITS_SCROLL 1
#define CONF_CREDITS_DELAY 200
#define CONF_SEQUENCE_BG_SCROLL 1
#define CONF_SEQUENCE_BG_GAP 30
#define CONF_INTRO_TICKS 200

// editor options.
#define CONF_EDITOR_CAM_ZOOM 0.06f
#define CONF_EDITOR_CAM_SPEED 0.1f
#define CONF_EDITOR_CAM_SPEED_FAST 0.3f
#define CONF_EDITOR_TYPE_INDICATOR_SIZE 70
#define CONF_EDITOR_BAR_SIZE 140
#define CONF_EDITOR_SAVE_INDICATOR_SIZE 15

#endif
