#ifndef CONF_H
#define CONF_H

#include <SDL.h>

// window options.
#define CONF_WND_TITLE "Cubic Jumping"
#define CONF_WND_WIDTH 800
#define CONF_WND_HEIGHT 600
#define CONF_WND_FLAGS 0
#define CONF_REND_FLAGS 0

// keybind options.
#define CONF_KEY_LEFT SDLK_LEFT
#define CONF_KEY_RIGHT SDLK_RIGHT
#define CONF_KEY_JUMP SDLK_UP
#define CONF_KEY_FALL SDLK_DOWN
#define CONF_KEY_POWERJUMP SDLK_x
#define CONF_KEY_MENU SDLK_ESCAPE

// gamerule options.
#define CONF_TICK_MS 10
#define CONF_FRICTION 1.25f
#define CONF_WALL_SLIDE_FRICTION 1.25f
#define CONF_DRAG 1.005f
#define CONF_PLAYER_SIZE 0.8f
#define CONF_PLAYER_SPEED 0.025f
#define CONF_PLAYER_AIR_SPEED 0.0025f
#define CONF_PLAYER_JUMP_FORCE 0.3f
#define CONF_PLAYER_WALLJUMP_FORCE_X 0.15f
#define CONF_PLAYER_WALLJUMP_FORCE_Y 0.25f
#define CONF_PLAYER_POWERJUMP_FORCE_X 0.4f
#define CONF_PLAYER_POWERJUMP_FORCE_Y 0.2f
#define CONF_PLAYER_FALL_ACCEL 0.03f
#define CONF_PLAYER_DEATH_TICKS 100
#define CONF_GRAVITY 0.01f
#define CONF_RESTITUTION 0.85f
#define CONF_LAUNCH_FORCE_X 0.4f
#define CONF_LAUNCH_FORCE_Y 0.8f

// visual options.
#define CONF_DRAW_SCALE 50
#define CONF_SHOW_TRIGGERS 0 // 1 = show triggers, 0 = don't.
#define CONF_COLOR_BG {239, 239, 239}
#define CONF_COLOR_BG_SQUARE {232, 232, 232}
#define CONF_COLOR_PLAYER {255, 0, 0}
#define CONF_COLOR_TRIGGER_MSG {255, 179, 0}
#define CONF_COLOR_TRIGGER_KILL {210, 0, 0}
#define CONF_COLOR_TRIGGER_OPACITY 128
#define CONF_COLOR_PLAYER_TRACE_A {245, 164, 162}
#define CONF_COLOR_PLAYER_TRACE_B {146, 100, 154}
#define CONF_COLOR_PLAYER_SHARD_A {255, 0, 0}
#define CONF_COLOR_PLAYER_SHARD_B {128, 0, 0}
#define CONF_COLOR_GROUND {0, 0, 0}
#define CONF_COLOR_KILL {100, 0, 0}
#define CONF_COLOR_BOUNCE {0, 150, 200}
#define CONF_COLOR_LAUNCH {0, 255, 130}
#define CONF_COLOR_END {240, 190, 0}
#define CONF_COLOR_SWITCH_OFF {128, 140, 255}
#define CONF_COLOR_SWITCH_ON {255, 140, 255}
#define CONF_COLOR_TEXT {255, 255, 255}
#define CONF_COLOR_TEXT_OUTLINE {0, 0, 0}
#define CONF_COLOR_TEXT_BOX {70, 70, 70}
#define CONF_COLOR_TEXT_BOX_OPACITY 210
#define CONF_COLOR_BUTTON {110, 110, 110}
#define CONF_COLOR_BUTTON_HOVERED {190, 190, 190}
#define CONF_COLOR_BUTTON_PRESSED {10, 10, 10}
#define CONF_COLOR_OUTLINE {210, 210, 210}
#define CONF_COLOR_EDITOR_SAVED {0, 255, 0}
#define CONF_COLOR_EDITOR_UNSAVED {255, 0, 0}
#define CONF_COLOR_EDITOR_BOUNDARY {0, 255, 255}
#define CONF_COLOR_EDITOR_BOUNDARY_OPACITY 100
#define CONF_COLOR_EDITOR_SAVED {0, 255, 0}
#define CONF_COLOR_EDITOR_UNSAVED {255, 0, 0}
#define CONF_BG_SQUARE_SIZE 128
#define CONF_BG_SQUARE_GAP 16
#define CONF_BG_SQUARE_SPEED_X 0.2f
#define CONF_BG_SQUARE_SPEED_Y 0.1f
#define CONF_CAM_SPEED 0.05f
#define CONF_CAM_ZOOM_SPEED 0.025f
#define CONF_CAM_MIN_ZOOM 0.15f
#define CONF_CAM_MAX_ZOOM 0.9f
#define CONF_MAX_PARTICLES 512
#define CONF_PLAYER_TRACE_LIFETIME 80
#define CONF_PLAYER_TRACE_SIZE_A 0.8f
#define CONF_PLAYER_TRACE_SIZE_B 0.0f
#define CONF_PLAYER_TRACE_SPAWN_TICKS 2
#define CONF_PLAYER_SHARD_LIFETIME_RANGE 120
#define CONF_PLAYER_SHARD_SPEED_X_RANGE 0.2f
#define CONF_PLAYER_SHARD_SPEED_Y_RANGE 0.3f
#define CONF_PLAYER_SHARD_SIZE_A 0.6f
#define CONF_PLAYER_SHARD_SIZE_B 0.0f
#define CONF_PLAYER_SHARD_CNT 100
#define CONF_TEXT_SCALE 4
#define CONF_TEXT_OUTLINE_SCALE 2
#define CONF_TEXT_BOX_PADDING 10
#define CONF_TEXT_BOX_HEIGHT 140
#define CONF_BUTTON_PADDING 5
#define CONF_TIMER_OFF_X 10
#define CONF_TIMER_OFF_Y 10

// editor options.
#define CONF_EDITOR_CAM_ZOOM 0.06f
#define CONF_EDITOR_CAM_SPEED 0.1f
#define CONF_EDITOR_TYPE_INDICATOR_SIZE 70
#define CONF_EDITOR_BAR_SIZE 140
#define CONF_EDITOR_SAVE_INDICATOR_SIZE 15

#endif
